<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Les;

/**
 * LesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLesByInstructor($insId){
        $em=$this->getEntityManager();
        $member = $em->getRepository(Les::class)->findOneBy(['id' => $insId]);

        $query=$em->createQuery("SELECT a FROM AppBundle:Les a WHERE :insid = a.user");

        $query->setParameter('insid',$insId);
        return $query->getResult();
    }
    public function getLesNotByInstructor($insId){
        $em=$this->getEntityManager();
        $member = $em->getRepository(Les::class)->findOneBy(['id' => $insId]);

        $query=$em->createQuery("SELECT a FROM AppBundle:Les a WHERE :insid != a.user");

        $query->setParameter('insid',$insId);
        return $query->getResult();
    }
//    public function getLesById($lesId){
//        $em=$this->getEntityManager();
//        $les=$em->getRepository(Les::class)->findOneBy(['id' => $lesId]);
//
//        $query=$em->createQuery("SELECT a FROM FROM AppBundle:Les a WHERE :lesid = a.id");
//
//        $query->setParameter('lesid', $lesId);
//        return $query->getResult();
//    }
}
