<?php

namespace AppBundle\Repository;

/**
 * LesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LesRepository extends \Doctrine\ORM\EntityRepository
{
}
